name: Build and deploy develop branch to S3 Staging
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      TEST_NOW: ${{ vars.TEST_VAR }}
      AWS_REGION: ca-central-1
      WEBHOSTING_BUCKET_NAME: staging.cms-widget.footlight.io
    runs-on: ubuntu-22.04
    container:
      image: sleavely/node-awscli:14.x
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
  copytos3:
    uses: keithweaver/aws-s3-github-action@v1.0.0
    with:
      command: cp
      source: ./build
      destination: s3://staging.cms-widget.footlight.io/
    secrets:
      aws_access_key_id: ${{ secrets.S3_ACCESS_KEY_ID}}
      aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      aws_region: ca-central-1
      flags: --acl public-read --delete --cache-control max-age=3600
