name: Build and deploy develop branch to S3 Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy_and_copy:
    runs-on: ubuntu-22.04
    container:
      image: sleavely/node-awscli:14.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - run: echo "TEST_NOW=${{ secrets.S3_SECRET_ACCESS_KEY }}"
      - run: echo "TEST_NOW=${{ secrets.S3_ACCESS_KEY_ID }}"
      - name: Copy to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./build
          destination: s3://staging.cms-widget.footlight.io/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws_region: ca-central-1
          flags: --acl public-read --delete --cache-control max-age=3600

          
          